# Generated by Django 6.0.2 on 2026-03-02 19:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('nombre_usuario', models.CharField(max_length=200)),
                ('id_tipo_documento', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id_rol', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
