# Generated by Django 6.0.2 on 2026-03-01 22:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notas',
            fields=[
                ('id_nota', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('id_inscripcion', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('corte', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del profesor')),
            ],
        ),
    ]
